server:
  port: 7081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_store?Schema=public
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
